/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abel
 */

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.*;
import java.util.ArrayList;

public class NewApplication extends javax.swing.JFrame {

    /**
     * Creates new form NewApplication
     */
    
    
      Arbol a;
      Arbol cursor;
      public void actualiza(){
           jPanel1.removeAll();
           
        ArrayList aux=a.inOrden();
        for(int i=0;i<aux.size();i++)
        { Nodo n=(Nodo)aux.get(i);
         Arbol w=new Arbol(n);   
        JButton t=(JButton)w.raiz.valor;
        t.setVisible(true);
            
        jPanel1.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(i*100,w.nivel()*100, 50, 30));
           
        
        }
        
        
        aux=a.inOrden();
        for(int i=0;i<aux.size();i++)
        { Nodo n=(Nodo)aux.get(i);
          JButton b1=(JButton)n.valor;     
           for(int j=0;j<n.hijos.size();j++)
             {Nodo m=(Nodo)n.hijos.get(j);
             JButton b2=(JButton)m.valor;
             jPanel1.getGraphics().drawLine(b1.getLocation().x,b1.getLocation().y,
                                            b2.getLocation().x,b2.getLocation().y);
             }
               }
           
       eshoja.setText(cursor.eshoja()+"");
       altura.setText(cursor.altura()+"");
       peso.setText(cursor.peso()+"");
       ancho.setText(cursor.ancho()+"");
       nivel.setText(cursor.nivel()+"");
       raiz.setText(((JButton)cursor.raiz.valor).getText());
    
    
      }
      
     
      
    
    public NewApplication() {
        initComponents();
       JButton x=new JButton();
        cursor=a=new Arbol(x);
       
        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        }); 
       
        
        actualiza();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        valor = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        addhijo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        podarhijo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        raiz = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        eshoja = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        altura = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        peso = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ancho = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nivel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentResized(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 540));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(3, 2));

        jButton1.setText("addValor(x)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jPanel3.add(valor);

        jButton2.setText("addHijo(x)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jPanel3.add(addhijo);

        jButton3.setText("podarHijo(x)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jPanel3.add(podarhijo);

        jPanel4.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(6, 2, 3, 3));

        jLabel5.setText("raiz");
        jPanel2.add(jLabel5);
        jPanel2.add(raiz);

        jLabel1.setText("esHoja()");
        jPanel2.add(jLabel1);
        jPanel2.add(eshoja);

        jLabel2.setText("altura()");
        jPanel2.add(jLabel2);
        jPanel2.add(altura);

        jLabel3.setText("peso()");
        jPanel2.add(jLabel3);
        jPanel2.add(peso);

        jLabel8.setText("ancho()");
        jPanel2.add(jLabel8);
        jPanel2.add(ancho);

        jLabel4.setText("nivel()");
        jPanel2.add(jLabel4);
        jPanel2.add(nivel);

        jPanel4.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 200, 300));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 200, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   ((JButton)cursor.raiz.valor).setText(valor.getText());
   raiz.setText(valor.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         JButton X=new JButton(addhijo.getText());   
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });
        
         cursor.addHijo(new Arbol(X));
      actualiza();
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
   actualiza();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentResized
actualiza();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentResized

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     a.podarHijo(cursor);
     for(int i=0;i<a.raiz.hijos.size();i++)
     new Arbol((Nodo)a.raiz.hijos.get(i)).podarHijo(cursor);
     
     cursor=a;
     jPanel1.repaint();
   actualiza();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

   public void ActionPerformed(java.awt.event.ActionEvent evt)
   {JButton b=((JButton)evt.getSource());
    Nodo n=a.buscar(new Arbol(b));
   cursor=new Arbol(n);
   actualiza();
   }
    

   
   
   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addhijo;
    private javax.swing.JLabel altura;
    private javax.swing.JLabel ancho;
    private javax.swing.JLabel eshoja;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nivel;
    private javax.swing.JLabel peso;
    private javax.swing.JTextField podarhijo;
    private javax.swing.JLabel raiz;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables

    
    
    
}
